[functions]
external_node_modules = ["express"]
node_bundler = "esbuild"
directory = "./netlify/functions/"

[[redirects]]
force = true
from = "/api/*"
status = 200
to = "/.netlify/functions/api/:splat"

[build]
base = "client"
command = "npm run build"
